apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      type: myapp
  template:
    metadata:
      labels:
        type: myapp
    spec:
      containers:
        - name: container1
          image: machhindrakangane/sunbeam
          ports:
            - containerPort: 4000
              protocol: TCP